# Generated by Django 3.2 on 2021-08-25 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
